name: MasterBuild

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

env:
  CONTAINER_NAME: uwhackweeks/oceanhackweek
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
      
    - name: Cache Docker layers
      uses: actions/cache@v2.1.6
      with:
        path: /tmp/.buildx-cache
        key: ohw-docker-buildx-${{ github.sha }}
        restore-keys: |
          ohw-docker-buildx-

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        IMAGE_SPEC="${CONTAINER_NAME}:${DOCKER_TAG}"
        echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
        echo "::set-env name=IMAGE_SPEC::${IMAGE_SPEC}"

    - name: "Login to Docker Hub"
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      uses: docker/build-push-action@v2.6.1
      with:
        tags: ${{ env.CONTAINER_NAME }}:latest,${{ env.CONTAINER_NAME }}:${{env.DOCKER_TAG}}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        load: true

    - name: Export Full Conda Environment
      run: |
        docker run ${CONTAINER_NAME}:latest conda list --explicit > conda-packages.txt

    - name: Archive Conda Package List
      uses: actions/upload-artifact@v1
      with:
        name: conda-packages
        path: conda-packages.txt
    
    - name: Move Docker Cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
